#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ..= "cd .."
alias ....= "cd ...."
alias ......= "cd ......" 
alias sagu="sudo apt-get update"
alias sagi="sudo apt-get install"
alias brown="play -n synth brownnoise"

alias filesize="du -sh"

export MATLAB_JAVA=/usr/lib/jvm/java-7-openjdk-amd64/jre        

export DISPLAY=:0   

export LD_LIBRARY_PATH=/usr/local/lib

[ ! -d "$HOME/usr/src" ] && mkdir -p "$HOME/usr/src"
export PKG_CONFIG_PATH="${HOME}/usr/lib/pkgconfig:${PKG_CONFIG_PATH}"
export CPATH="${HOME}/usr/include:${CPATH}"

export MANPATH="${HOME}/usr/share/man:${MANPATH}"

export LD_LIBRARY_PATH="${HOME}/usr/lib:${LD_LIBRARY_PATH}"

export PATH="${HOME}/usr/bin:${PATH}"
export PATH=~/.npm-global/bin:$PATH
export PATH="/home/hammas/scripts:$PATH"
# added by Miniconda3 installer
export PATH="/home/hammas/miniconda3/bin:$PATH"

zstyle ':completion::complete:*' use-cache 1

